#!/bin/bash

#-------------------------------------------------------------------------------
# Copyright (C) 2018 Dominik Salvet
# SPDX-License-Identifier: MIT
#-------------------------------------------------------------------------------
# Parameters:
#     $1 - installation directory path
#-------------------------------------------------------------------------------

## SOFTWARE DEPENDECIES

sw_missing=0
# software is missing if at least one piece of software is missing
$(type [ > /dev/null); ((sw_missing |= $?))
$(type echo > /dev/null); ((sw_missing |= $?))
$(type read > /dev/null); ((sw_missing |= $?))
$(type rm > /dev/null); ((sw_missing |= $?))
$(type sed > /dev/null); ((sw_missing |= $?))

# check if some software is missing
if [ "$sw_missing" -ne 0 ]; then
    echo 'Required software is missing, uninstallation canceled.'
    exit 1
fi

## USER SETUP

# check if running as root
if [ "$EUID" -ne 0 ]; then
    echo 'Please run as root, uninstallation canceled.'
    exit 2
fi

# user confirmation
read -p 'Do you really want to uninstall ASUS ZenBook UX430UA configuration? [y/n] ' user_agreed
if [ $user_agreed != y ]; then
    echo 'Uninstallation canceled.'
    exit
fi

# check if installed in given installation directory
if [ ! -e $1/jack-config ] && [ ! -e $1/fan-config ]; then
    echo 'The program is not installed in the "'"$1"'"" directory, uninstallation canceled.'
    exit 3
fi

## UNINSTALLATION

echo
echo '================================================================================'
echo
echo 'Uninstalling ...'

# revert less aggressive fan speed policy setup
rm -f /lib/systemd/system-sleep/fan-config
sed -i -e '\|'"$1"'/fan-config|d' /etc/rc.local
rm -f $1/fan-config
# acpi_call is not removed from /etc/modules (in case some program uses it)

# revert 3.5 mm jack output volume setup
rm -f /lib/systemd/system-sleep/jack-config
sed -i -e '\|'"$1"'/jack-config|d' /etc/rc.local
rm -f $1/jack-config

# notice
echo
echo 'Notice:'
echo 'The "acpi_call" line must be manually removed from the "/etc/modules" file, if it is not used.'
echo 'The "alsa-tools" and "acpi-call-dkms" packages must be uninstalled manually, if they are not used.'

# finished
echo
echo '================================================================================'
echo
echo 'Done! In order to apply the changes, reboot your machine.'
