#!/bin/bash

#-------------------------------------------------------------------------------
# Copyright (C) 2018 Dominik Salvet
# SPDX-License-Identifier: MIT
#-------------------------------------------------------------------------------
# Parameters:
#     $1 - installation directory path
#-------------------------------------------------------------------------------

## SOFTWARE DEPENDECIES

sw_missing=0
# software is missing if at least one piece of software is missing
type [ > /dev/null; ((sw_missing |= $?))
type echo > /dev/null; ((sw_missing |= $?))
type read > /dev/null; ((sw_missing |= $?))
type rm > /dev/null; ((sw_missing |= $?))
type sed > /dev/null; ((sw_missing |= $?))

# check if some software is missing
if [ $sw_missing -ne 0 ]; then
    echo 'Required software is missing, uninstallation canceled.'
    exit 1
fi

## USER SETUP

# check if running as root
if [ $EUID -ne 0 ]; then
    echo 'Please run as root, uninstallation canceled.'
    exit 2
fi

# check installed files
jack_config_exist=n; if [ -e "$1/jack-config" ]; then jack_config_exist=y; fi
fan_config_exist=n; if [ -e "$1/fan-config" ]; then fan_config_exist=y; fi

# check if the program is installed in given installation directory
if [ $jack_config_exist = n ] && [ $fan_config_exist = n ]; then
    echo "The program is not installed in given \"$1\" directory, uninstallation canceled."
    exit 3
fi

# summary
echo 'Summary:'
if [ $jack_config_exist = y ]; then echo 'The 3.5 mm jack output volume will be set to the system default.'; fi
if [ $fan_config_exist = y ]; then echo 'The fan speed policy will be set to the system default.'; fi

# user confirmation
echo
read -p 'Are you really sure to continue? [y/n] ' user_agreed
if [ "$user_agreed" != y ]; then
    echo 'Uninstallation canceled.'
    exit
fi

## UNINSTALLATION

echo
echo '================================================================================'
echo
echo 'Uninstalling ...'

if [ $fan_config_exist = y ]; then
    # revert less aggressive fan speed policy setup
    rm -f /lib/systemd/system-sleep/fan-config
    sed -i -e '\!^[^#]*'"$1"'/fan-config\( .*\|\s*\)$!d' /etc/rc.local
    rm -f -- "$1/fan-config"
    # acpi_call is not removed from /etc/modules (in case some program uses it)
fi

if [ $jack_config_exist = y ]; then
    # revert 3.5 mm jack output volume setup
    rm -f /lib/systemd/system-sleep/jack-config
    sed -i -e '\!^[^#]*'"$1"'/jack-config\( .*\|\s*\)$!d' /etc/rc.local
    rm -f -- "$1/jack-config"
fi

# notice
echo
echo 'Notice:'
echo 'The "acpi_call" line must be manually removed from the "/etc/modules" file, if it is not used.'
echo 'The "alsa-tools" and "acpi-call-dkms" packages must be uninstalled manually, if they are not used.'

# finished
echo
echo '================================================================================'
echo
echo 'Done! In order to apply the changes, reboot your machine.'
